name: iot mgnt telemetry - baseline

# volumes:
#   pgdata:

networks:
  public_network:
    driver: bridge
  private_network:
    driver: bridge
    internal: true

services:
  postgres:
    container_name: postgres
    image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/iot-mgnt-telemetry-pgdb:dev
    # image: pgdb
    build:
      context: ./pgdb/
      dockerfile: Dockerfile
    env_file:
      - fastapi/.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    networks:
      # - public_network
      - private_network
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "config_file=/config/dev.conf"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 30
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2028M
        reservations:
          cpus: "0.5"
          memory: 1024M

  fastapi01:
    container_name: fastapi01
    # image: 099139718958.dkr.ecr.ca-central-1.amazonaws.com/iot-mgnt-telemetry-fastapi:dev
    # image: simonangelfong/demo-ecs-svc-fastapi
    # image: fastapi
    build:
      context: ./fastapi/
      dockerfile: Dockerfile
    environment:
      - APP_NAME=local test
      # - CORS=http://localhost,http://localhost:8080,https://localhost
      - ENV=baseline
      - DEBUG=true
      - POSTGRES__HOST=postgres
      - POSTGRES__PORT=5432
      - POSTGRES__USER=app_user
      - POSTGRES__DB=app_db
      - POSTGRES__PASSWORD=postgres
    networks:
      # - public_network
      - private_network
    ports:
      - 8000:8000
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/var/www/html
    networks:
      - public_network
      - private_network
    ports:
      - "8080:8080"
    depends_on:
      - fastapi01


