name: Baseline - Apply

on:
  workflow_dispatch:
  push:
    branches:
      - "feature-baseline-testing" # testing branch
    paths:
      - "app/fastapi/**"
      - "aws/sol_baseline/**"
      - ".github/workflows/baseline-cd-apply.yaml"

concurrency:
  group: baseline-cd-apply-${{ github.ref_name }}
  cancel-in-progress: false # keep in-progress jobs

permissions:
  id-token: write # OIDC
  contents: read

jobs:
  ecr-push:
    name: Baseline-Push Image to ECR(${{ matrix.service.name }})
    runs-on: ubuntu-latest
    environment: baseline
    strategy:
      fail-fast: false
      matrix:
        service:
          - name: fastapi
            docker_context: app/fastapi
          - name: flyway
            docker_context: app/flyway

    env:
      DIR_DOCKFILE: ${{ matrix.service.docker_context }} # dockfile path
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{matrix.service.name}}"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ECR_REPOSITORY }}

      - name: Build and push Docker image
        id: build-push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: ${{ env.DIR_DOCKFILE }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ env.ECR_REPOSITORY }}
            ${{ env.ECR_REPOSITORY }}:${{ github.sha }}

      - name: Send email notification (on failure)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT }} ${{ matrix.service.name }} (${{ vars.ENV }})"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>GitHub Actions CI/CD Notification</h2>
            <p><b>Project</b>: ${{ vars.PROJECT }} (service: ${{ matrix.service.name }})</p>
            <p><b>Repository</b>: ${{ github.repository }}</p>
            <p><b>Env</b>: ${{ vars.ENV }}</p>
            <p><b>Job</b>: ${{ github.job }}</p>
            <p><b>Status</b>: ${{ job.status }}</p>
            <p><b>Branch</b>: ${{ github.ref }}</p>
            <p><b>Workflow</b>: ${{ github.workflow }}</p>
            <p><b>Commit</b>: ${{ github.sha }}</p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

  deploy:
    name: Baseline-Deploy(AWS)
    needs:
      - ecr-push
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: baseline
    env:
      TF_DIR: aws/sol_${{vars.ENV}}
      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_env: ${{ vars.ENV }}
      TF_VAR_db_name: ${{ secrets.DB_NAME }}
      TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
      TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
      TF_VAR_db_app_pwd: ${{ secrets.DB_APP_PWD }}
      TF_VAR_db_readonly_pwd: ${{ secrets.DB_READONLY_PWD }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CF_ZONE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Terraform plugin cache
        run: |
          mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
          echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}-${{ hashFiles('aws/.terraform.lock.hcl') }}

      - name: Terraform init - S3 backend
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform init -reconfigure -input=false \
            -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="key=${{ vars.PROJECT }}/${{ vars.ENV }}/terraform.tfstate" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform fmt -check -recursive -no-color
          terraform validate -no-color

      - name: Deploy - Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        id: deploy-plan
        run: terraform plan -out=tfplan -input=false -no-color

      - name: Deploy - Show plan (JSON)
        working-directory: ${{ env.TF_DIR }}
        run: terraform show -json tfplan > tfplan.json

      - name: Deploy - Save plan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-bundle-deploy
          path: |
            ${{ env.TF_DIR }}/tfplan
            ${{ env.TF_DIR }}/tfplan.json
          retention-days: 3

      - name: Deploy - Terraform Apply
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -no-color tfplan

      - name: Initial RDS
        working-directory: ${{ env.TF_DIR }}
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          set -euo pipefail

          PARAMS_JSON="$(terraform output -json flyway_task_param)"

          CLUSTER=$(echo "$PARAMS_JSON" | jq -r '.cluster')
          TASK_DEF=$(echo "$PARAMS_JSON" | jq -r '.task_definition')
          LAUNCH_TYPE=$(echo "$PARAMS_JSON" | jq -r '.launch_type')
          SUBNETS=$(echo "$PARAMS_JSON" | jq -r '.subnets | join(",")')
          SGS=$(echo "$PARAMS_JSON" | jq -r '.security_groups | join(",")')

          echo "Cluster: $CLUSTER"
          echo "Task definition: $TASK_DEF"
          echo "Subnets ID: $SUBNETS"
          echo "Security groups ID: $SGS"

          TASK_ARN=$(
            aws ecs run-task \
              --cluster "$CLUSTER" \
              --task-definition "$TASK_DEF" \
              --launch-type "$LAUNCH_TYPE" \
              --network-configuration "awsvpcConfiguration={subnets=[$SUBNETS],securityGroups=[$SGS]}" \
              --region "$AWS_REGION" \
              --query 'tasks[0].taskArn' \
              --output text
          )

          echo "Waiting for Flyway task to finish..."
          aws ecs wait tasks-stopped \
            --cluster "$CLUSTER" \
            --tasks "$TASK_ARN" \
            --region "$AWS_REGION"

          echo "Flyway migration task completed successfully."

      - name: Send email notification
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} (${{vars.ENV}})"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>GitHub Actions CI/CD Notification</h2>
            <p><b>Project</b>: ${{ vars.PROJECT}}</p>
            <p><b>Repository</b>: ${{ github.repository }}</p>
            <p><b>Env</b>: ${{ vars.ENV }}</p>
            <p><b>Job</b>: ${{ github.job }}</p>
            <p><b>Status</b>: ${{ job.status }}</p>
            <p><b>Branch</b>: ${{ github.ref }}</p>
            <p><b>Workflow</b>: ${{ github.workflow }}</p>
            <p><b>Commit</b>: ${{ github.sha }}</p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

      - name: Output
        id: output
        working-directory: ${{ env.TF_DIR }}
        run: |
          echo "BASE_URL=$(terraform output dns_url)" >> "$GITHUB_OUTPUT"
    outputs:
      BASE_URL: ${{ steps.output.outputs.BASE_URL }}

  testing:
    name: Baseline-Testing
    needs: deploy
    runs-on: ubuntu-latest
    environment: baseline
    env:
      DIR_LOAD_TESTING: k6/script
      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
      TF_VAR_project: ${{ vars.PROJECT }}
      TF_VAR_env: ${{ vars.ENV }}
      # TF_VAR_dns_domain: ${{ vars.DNS_DOMAIN }}
      # TF_VAR_aws_region: ${{ vars.AWS_REGION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: test
        run: |
          echo "${{ needs.deploy.outputs.BASE_URL}}

      # - name: Smoke Testing
      #   uses: grafana/run-k6-action@v1
      #   id: smoke-testing
      # env:
      #   K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
      #   K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
  #       with:
  #         debug: true
  #         fail-fast: true
  #         flags: --env DOMAIN=${{ env.TF_VAR_dns_domain }} --env ENV=${{ vars.ENV }}
  #         path: |
  #           ${{ env.DIR_LOAD_TESTING }}/test_smoke.js

  #     - name: Send email notification
  #       if: always()
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 465
  #         secure: true
  #         username: ${{ secrets.EMAIL_USERNAME }}
  #         password: ${{ secrets.EMAIL_PASSWORD }}
  #         subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} (${{vars.ENV}})"
  #         to: ${{ secrets.EMAIL_USERNAME }}
  #         from: ${{ secrets.EMAIL_USERNAME }}
  #         html_body: |
  #           <h2>GitHub Actions CI/CD Notification</h2>
  #           <p><b>Project</b>: ${{ vars.PROJECT}}</p>
  #           <p><b>Repository</b>: ${{ github.repository }}</p>
  #           <p><b>Env</b>: ${{ vars.ENV }}</p>
  #           <p><b>Job</b>: ${{ github.job }}</p>
  #           <p><b>Status</b>: ${{ job.status }}</p>
  #           <p><b>Branch</b>: ${{ github.ref }}</p>
  #           <p><b>Workflow</b>: ${{ github.workflow }}</p>
  #           <p><b>Commit</b>: ${{ github.sha }}</p>
  #           <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>

  # destroy:
  #   name: Destroy(Prod)
  #   needs: set-tf-ini
  #   if: needs.set-tf-ini.outputs.TF_DEPLOY_FLAG == 'false'
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 90
  #   environment: prod
  #   env:
  #     TF_DIR: aws
  #     TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
  #     TF_VAR_aws_region: ${{ vars.AWS_REGION }}
  #     TF_VAR_env: ${{ vars.ENV }}
  #     TF_VAR_aws_ecr_fastapi: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-fastapi"
  #     TF_VAR_aws_ecr_pgdb: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-pgdb"
  #     TF_VAR_aws_ecr_redis: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-redis"
  #     TF_VAR_app_pgdb_host: ${{ vars.APP_PGDB_HOST }}
  #     TF_VAR_app_pgdb_db: ${{ vars.APP_PGDB_DB }}
  #     TF_VAR_app_pgdb_user: ${{ vars.APP_PGDB_USER }}
  #     TF_VAR_app_pgdb_pwd: ${{ secrets.APP_PGDB_PWD }}
  #     TF_VAR_app_redis_host: ${{ vars.APP_REDIS_HOST }}
  #     TF_VAR_app_pgdb_init_user: ${{ vars.APP_PGDB_INIT_USER }}
  #     TF_VAR_app_pgdb_init_db: ${{ vars.APP_PGDB_INIT_DB }}
  #     TF_VAR_app_pgdb_init_pwd: ${{ secrets.APP_PGDB_INIT_PWD }}
  #     TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
  #     TF_VAR_cloudflare_zone_id: ${{ secrets.CF_ZONE_ID }}

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3
  #       with:
  #         terraform_version: ${{ vars.TF_VERSION }}

  #     - name: Configure AWS credentials (OIDC)
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
  #         aws-region: ${{ vars.AWS_REGION }}

  #     - name: Configure Terraform plugin cache
  #       run: |
  #         mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

  #     - name: Cache Terraform plugins
  #       uses: actions/cache@v4
  #       with:
  #         path: ${{ env.TF_PLUGIN_CACHE_DIR }}
  #         key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}-${{ hashFiles('aws/.terraform.lock.hcl') }}

  #     - name: Terraform init - S3 backend
  #       working-directory: ${{ env.TF_DIR }}
  #       run: |
  #         terraform init -reconfigure -input=false \
  #           -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
  #           -backend-config="region=${{ vars.AWS_REGION }}" \
  #           -backend-config="key=${{ vars.PROJECT }}-${{vars.APP}}/${{ vars.ENV }}/terraform.tfstate" \
  #           -backend-config="encrypt=true"

  #     - name: Terraform Validate
  #       working-directory: ${{ env.TF_DIR }}
  #       run: |
  #         terraform fmt -check -recursive -no-color
  #         terraform validate -no-color

  #     - name: Destroy - Terraform Plan
  #       working-directory: ${{ env.TF_DIR }}
  #       id: plan-destroy
  #       run: terraform plan -out=tfplan-destroy -input=false -no-color -destroy

  #     - name: Destroy - Show plan (JSON)
  #       working-directory: ${{ env.TF_DIR }}
  #       run: terraform show -json tfplan-destroy > tfplan-destroy.json

  #     - name: Destroy - Save plan artifacts
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: tfplan-bundle-destroy
  #         path: |
  #           ${{ env.TF_DIR }}/tfplan-destroy
  #           ${{ env.TF_DIR }}/tfplan-destroy.json
  #         retention-days: 3

  #     - name: Destroy - Terraform Apply
  #       working-directory: ${{ env.TF_DIR }}
  #       run: terraform apply -auto-approve -no-color tfplan-destroy

  #     - name: Send email notification
  #       if: always()
  #       uses: dawidd6/action-send-mail@v3
  #       with:
  #         server_address: smtp.gmail.com
  #         server_port: 465
  #         secure: true
  #         username: ${{ secrets.EMAIL_USERNAME }}
  #         password: ${{ secrets.EMAIL_PASSWORD }}
  #         subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
  #         to: ${{ secrets.EMAIL_USERNAME }}
  #         from: ${{ secrets.EMAIL_USERNAME }}
  #         html_body: |
  #           <h2>GitHub Actions CI/CD Notification</h2>
  #           <p><b>Project</b>: ${{ vars.PROJECT}}</p>
  #           <p><b>Application</b>: ${{ vars.APP}}</p>
  #           <p><b>Repository</b>: ${{ github.repository }}</p>
  #           <p><b>Env</b>: ${{ vars.ENV }}</p>
  #           <p><b>Job</b>: ${{ github.job }}</p>
  #           <p><b>Status</b>: ${{ job.status }}</p>
  #           <p><b>Branch</b>: ${{ github.ref }}</p>
  #           <p><b>Workflow</b>: ${{ github.workflow }}</p>
  #           <p><b>Commit</b>: ${{ github.sha }}</p>
  #           <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
