name: Manually Destroy(Prod)

on:
  workflow_dispatch:
    # require input
    inputs:
      confirm_destroy:
        description: "Type YES to confirm destroying PROD infrastructure"
        required: true
        type: string

  schedule:
    # 17:00 toronto time
    - cron: "0 22 * * *"  

concurrency:
  group: prod-destroy-${{ github.ref_name }}
  cancel-in-progress: false # keep in-progress jobs

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    name: Destroy(Prod)
    # destroy only if yes or schedult
    if: >
      (github.event_name == 'workflow_dispatch' &&
       github.event.inputs.confirm_destroy == 'YES') ||
      (github.event_name == 'schedule')
    runs-on: ubuntu-latest
    timeout-minutes: 90
    environment: prod
    env:
      TF_DIR: aws
      TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
      TF_VAR_aws_region: ${{ vars.AWS_REGION }}
      TF_VAR_env: ${{ vars.ENV }}
      TF_VAR_aws_ecr_fastapi: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-fastapi"
      TF_VAR_aws_ecr_pgdb: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-pgdb"
      TF_VAR_aws_ecr_redis: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/${{ vars.PROJECT }}-${{vars.APP}}-redis"
      TF_VAR_app_pgdb_host: ${{ vars.APP_PGDB_HOST }}
      TF_VAR_app_pgdb_db: ${{ vars.APP_PGDB_DB }}
      TF_VAR_app_pgdb_user: ${{ vars.APP_PGDB_USER }}
      TF_VAR_app_pgdb_pwd: ${{ secrets.APP_PGDB_PWD }}
      TF_VAR_app_redis_host: ${{ vars.APP_REDIS_HOST }}
      TF_VAR_app_pgdb_init_user: ${{ vars.APP_PGDB_INIT_USER }}
      TF_VAR_app_pgdb_init_db: ${{ vars.APP_PGDB_INIT_DB }}
      TF_VAR_app_pgdb_init_pwd: ${{ secrets.APP_PGDB_INIT_PWD }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CF_API_TOKEN }}
      TF_VAR_cloudflare_zone_id: ${{ secrets.CF_ZONE_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TF_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Configure Terraform plugin cache
        run: |
          mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
          echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: ${{ env.TF_PLUGIN_CACHE_DIR }}
          key: ${{ runner.os }}-terraform-${{ vars.TF_VERSION }}

      - name: Terraform init - S3 backend
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform --version
          terraform init -reconfigure -input=false \
            -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
            -backend-config="region=${{ vars.AWS_REGION }}" \
            -backend-config="key=${{ vars.PROJECT }}-${{vars.APP}}/${{ vars.ENV }}/terraform.tfstate" \
            -backend-config="encrypt=true"

      - name: Terraform Validate
        working-directory: ${{ env.TF_DIR }}
        run: |
          terraform fmt -check -recursive -no-color
          terraform validate -no-color

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        id: plan
        run: terraform plan -out=tfplan-destroy -input=false -no-color -destroy

      - name: Show plan (JSON) - Destroy
        working-directory: ${{ env.TF_DIR }}
        run: terraform show -json tfplan-destroy > tfplan-destroy.json

      - name: Save plan artifacts - Destroy
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-bundle-destroy-manual
          path: |
            ${{ env.TF_DIR }}/tfplan-destroy
            ${{ env.TF_DIR }}/tfplan-destroy.json
          retention-days: 3

      - name: Terraform Destroy
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -no-color tfplan-destroy

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "${{ job.status }} - ${{ github.workflow }}: ${{ vars.PROJECT}} ${{vars.APP}} (${{vars.ENV}})"
          to: ${{ secrets.EMAIL_USERNAME }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <h2>GitHub Actions CI/CD Notification</h2>
            <p><b>Project</b>: ${{ vars.PROJECT}}</p>
            <p><b>Application</b>: ${{ vars.APP}}</p>
            <p><b>Repository</b>: ${{ github.repository }}</p>
            <p><b>Env</b>: ${{ vars.ENV }}</p>
            <p><b>Job</b>: ${{ github.job }}</p>
            <p><b>Status</b>: ${{ job.status }}</p>
            <p><b>Branch</b>: ${{ github.ref }}</p>
            <p><b>Workflow</b>: ${{ github.workflow }}</p>
            <p><b>Commit</b>: ${{ github.sha }}</p>
            <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
