name: "Workflow-Prod-Web-Deploy"

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - "app/html/**"

# read write
permissions:
    contents: read
    id-token: write

# multiple trigger
concurrency:
    group: prod-web-deploy-${{ github.workflow }}-${{ github.ref_name }}
    cancel-in-progress: true # Cancel older runs

jobs:
    deploy_prod:
        name: Production-Web-Deploy
        runs-on: ubuntu-latest
        environment: Prod
        timeout-minutes: 60
        env:
            TF_VERSION: 1.14.0
            TF_DIR: aws/web
            TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
            TF_VAR_project: ${{ vars.PROJECT }}
            TF_VAR_env: ${{ vars.ENV }}
            TF_VAR_aws_region: ${{ vars.AWS_REGION }}
            TF_VAR_domain_name: ${{vars.DOMAIN_NAME}}
            TF_VAR_cloudflare_api_token: ${{secrets.CF_API_TOKEN}}
            TF_VAR_cloudflare_zone_id: ${{secrets.CF_ZONE_ID}}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ vars.TF_VERSION }}

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN }}
                  aws-region: ${{ env.TF_VAR_aws_region }}

            - name: Configure Terraform plugin cache
              run: |
                  mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
                  echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

            - name: Cache Terraform plugins
              uses: actions/cache@v4
              with:
                  path: ${{ env.TF_PLUGIN_CACHE_DIR }}
                  key: ${{ runner.os }}-terraform-${{ env.TF_VERSION }}-${{ vars.ENV }}-${{ hashFiles('aws/.terraform.lock.hcl') }}

            - name: Terraform init - S3 backend
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform init -reconfigure -input=false \
                    -backend-config="bucket=${{ vars.AWS_BACKEND_BUCKET }}" \
                    -backend-config="region=${{ vars.AWS_REGION }}" \
                    -backend-config="key=${{ vars.PROJECT }}/${{ vars.ENV }}/terraform.tfstate" \
                    -backend-config="encrypt=true"

            - name: Deploy-Terraform Validate
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform fmt -check -recursive -no-color
                  terraform validate -no-color

            - name: Deploy-Terraform Plan
              working-directory: ${{ env.TF_DIR }}
              id: deploy-plan
              run: terraform plan -out=tfplan -input=false -no-color

            - name: Deploy-Show plan (JSON)
              working-directory: ${{ env.TF_DIR }}
              run: terraform show -json tfplan > tfplan.json

            - name: Deploy-Save plan artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: "tfplan-deploy-${{ env.TF_VAR_env }}"
                  path: |
                      ${{ env.TF_DIR }}/tfplan
                      ${{ env.TF_DIR }}/tfplan.json
                  retention-days: 3

            - name: Deploy-Terraform Apply
              working-directory: ${{ env.TF_DIR }}
              run: terraform apply -auto-approve -no-color tfplan

            - name: Send email notification
              if: always()
              uses: dawidd6/action-send-mail@v3
              with:
                  server_address: smtp.gmail.com
                  server_port: 465
                  secure: true
                  username: ${{ secrets.EMAIL_USERNAME }}
                  password: ${{ secrets.EMAIL_PASSWORD }}
                  subject: "${{ job.status }}-${{ github.workflow }}: ${{ vars.PROJECT}} (${{vars.ENV}})"
                  to: ${{ secrets.EMAIL_USERNAME }}
                  from: ${{ secrets.EMAIL_USERNAME }}
                  html_body: |
                      <h2>GitHub Actions CI/CD Notification</h2>
                      <p><b>Project</b>: ${{ vars.PROJECT}}</p>
                      <p><b>Repository</b>: ${{ github.repository }}</p>
                      <p><b>Env</b>: ${{ vars.ENV }}</p>
                      <p><b>Job</b>: ${{ github.job }}</p>
                      <p><b>Status</b>: ${{ job.status }}</p>
                      <p><b>Branch</b>: ${{ github.ref }}</p>
                      <p><b>Workflow</b>: ${{ github.workflow }}</p>
                      <p><b>Commit</b>: ${{ github.sha }}</p>
                      <p><a href="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}">View Workflow Run</a></p>
